### ISSUE TITLE
Update the cascade wrt new version

### ISSUE THREAD

**Issue by ganeshkharad** [shantamsultania/numberplate_recog#1]
https://github.com/shantamsultania/numberplate_recog/blob/6c5512e16dd100e48827aae167e3a3adb2576fda/number%20plate.py#L3

use below syntax for updated open-cv - 
cas = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_russian_plate_number.xml')

**Comment by shantamsultania** [comment]
cool do you want to do it if yes I can assign it to you that why you will be able to make a contribution to my project also what say?

**Comment by ganeshkharad2** [comment]
> cool do you want to do it if yes I can assign it to you that why you will be able to make a contribution to my project also what say?

okay, Just assign it on this id

**Comment by shantamsultania** [comment]
assigned it to you man @ganeshkharad2

**Comment by ganeshkharad2** [comment]
> assigned it to you man @ganeshkharad2

yes

**Comment by shantamsultania** [comment]
hey, @ganeshkharad2 any progress?

**Comment by shantamsultania** [comment]
thanks for creating and contributing your PR has been successfully merged have a nice day ahead @ganeshkharad2
